#!/usr/bin/python
from time import sleep
from subprocess import check_output, run

# ip addr shows every network devices
# Show only the lines that start with numbers and print the second column (which contains the name of the device)
# Get only the devices that starts with 'w' ie, wireless devices
# I have only one wifi device so this works for me, if you want multiple ones, you might want to tweak something here
# this name is in the form wlan0: we don't need : at the end to use substr to remove it 
interface=check_output("""ip addr | awk '/^[0-9]/ {print $2}' | awk '/^w/ {print substr($0, 1, length($0)-1)}'""", shell=True).decode().strip()

def get_cat_values():
    recv_bytes = check_output("cat /sys/class/net/{}/statistics/rx_bytes".format(interface), shell=True)
    recv_bytes = recv_bytes.decode().strip()
    sent_bytes = check_output("cat /sys/class/net/{}/statistics/tx_bytes".format(interface), shell=True)
    sent_bytes = sent_bytes.decode().strip()
    return round(int(recv_bytes)/1024, 2), round(int(sent_bytes)/1024, 2)

r, s = get_cat_values()

while True:
    sleep(1)
    new_r, new_s = get_cat_values()
    dr, ds = round(new_r - r, 2), round(new_s - s, 2)
    r, s = new_r, new_s
    dl = "{:7.2f} KB".format(dr) if dr<1024 else "{:7.2f} MB".format(round(dr/1024, 2))
    up = "{:7.2f} KB".format(ds) if ds<1024 else "{:7.2f} MB".format(round(ds/1024, 2))
    run("""echo "%{{F#0f0}}{}  %{{F#f00}}{} " """.format(dl, up), shell=True)    

