#!/bin/bash

OPTIONS=(i3 urxvt polybar)

choice="$(for i in "${OPTIONS[@]}"; do echo "$i"; done | dmenu -i -l 10)"

echo $choice

case $choice in
    "i3")
        urxvt -e vim $HOME/.config/i3/config;;
    "urxvt")
        urxvt -e vim $HOME/.Xresources;;
    "polybar")
        urxvt -e vim $HOME/.config/polybar/config;;
    *)
esac
