#!/bin/bash

OPTIONS=(i3 urxvt polybar zsh)

CHOICE="$(for i in "${OPTIONS[@]}"; do echo "$i"; done | dmenu -i -p "Choose the config file: ")"

case $CHOICE in
    "i3")
        urxvt -e vim $HOME/.config/i3/config;;
    "urxvt")
        urxvt -e vim $HOME/.Xresources;;
    "polybar")
        urxvt -e vim $HOME/.config/polybar/config;;
    "zsh")
        urxvt -e vim $HOME/.zshrc;;
    *)
esac
