#!/bin/bash

OPTIONS=(i3 urxvt polybar zsh vim tmux)

CHOICE="$(for i in "${OPTIONS[@]}"; do echo "$i"; done | dmenu -i -p "Choose the config file: ")"

echo "$CHOICE"
case $CHOICE in
    "i3")
        i3-sensible-terminal -e vim $HOME/.config/i3/config;;
    "urxvt")
        i3-sensible-terminal -e vim $HOME/.Xresources;;
    "polybar")
        i3-sensible-terminal -e vim $HOME/.config/polybar/config;;
    "zsh")
        i3-sensible-terminal -e vim $HOME/.config/zsh/.zshrc;;
    "vim")
        i3-sensible-terminal -e vim $HOME/.vimrc;;
    "tmux")
        i3-sensible-terminal -e vim $HOME/.config/tmux/tmux.conf;;
    *)
esac
