#!/bin/bash

selected=$(systemctl list-unit-files --no-pager --type=service --no-legend | awk '{print $1}' | dmenu -i -p "Choose Service" )

if [[ -n "$selected" ]]; then
    action=$(echo -e "start\nhalt\nrestart" | dmenu -i -p "Choose Action")
    
    case "$action" in 
        "start")
            sudo systemctl start "$selected"
            if [[ $? -ne 0 ]]; then
                sudo -u anupam DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus notify-send -u critical -t 4000 "Could not start $selected"
            else
                sudo -u anupam DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus notify-send -u low -t 4000 "$selected has been started"
            fi
            ;;
        "halt")
            sudo systemctl stop "$selected"
            if [[ $? -ne 0 ]]; then
                sudo -u anupam DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus notify-send -u critical -t 4000 "Could not stop $selected"
            else
                sudo -u anupam DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus notify-send -u low -t 4000 "$selected has been stopped"
            fi
            ;;
        "restart")
            sudo systemctl restart "$selected"
            if [[ $? -ne 0 ]]; then
                sudo -u anupam DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus notify-send -u critical -t 4000 "Could not restart $selected"
            else
                sudo -u anupam DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus notify-send -u low -t 4000 "$selected has been restarted"
            fi
            ;;
        *)
            exit 0;;
    esac
fi
