#!/bin/bash

choice="$(man -k . | awk '{print $1}' | sort -u | dmenu -l 30 -p "Choose the man page for: ")"

# Check if the string is not null, -n and -z are opposite
if [ -n "$choice" ]; then
    man -Tpdf $choice| zathura -
fi
